force-app/main/default/objects/Error_Handling_Configuration__mdt.object
<CustomObject>
    <label>Error Handling Configuration</label>
    <pluralLabel>Error Handling Configurations</pluralLabel>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Email_on_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email on Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Log_Level__c</fullName>
        <label>Log Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Info</fullName>
                    <label>Info - Info, Error</label>
                </value>
                <value>
                    <fullName>Fine</fullName>
                    <label>Fine - Info,Warning,Error</label>
                </value>
                <value>
                    <fullName>Finest</fullName>
                    <label>Finest - Debug, Info, Warning, Error</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/Logger.cls
public abstract class Logger implements ILogger {
	
    protected Error_Handling_Configuration__mdt metadata;
    protected Boolean isSendEmail;
    protected String logLevel;
    
    public Logger(){}
    
    public Logger(Error_Handling_Configuration__mdt metadata){
        this.metadata = metadata;
        this.isSendEmail = metadata.Email_on_Error__c;
        this.logLevel = metadata.Log_Level__c;
    }

    public void sendEmail(Exception ex, String source, String referenceId, String referenceInfo){

        messaging.SingleEmailMessage email = new messaging.SingleEmailMessage();
        string[] address = new string[]{metadata.Email_Address__c};

        String subject =  'OrgName:  ' + UserInfo.getOrganizationName() + ' OrgId: ' + UserInfo.getOrganizationId() + ' at ' + Datetime.now().format();

        String textBody = 'Username:  ' + UserInfo.getUserName() + '\n' +
                          'RoleId:  ' + UserInfo.getUserRoleId() + '\n' +
                          'ProfileId:  ' + UserInfo.getProfileId() + '\n';

        if (source != null) {
            textBody += 'Source:  ' + source + '\n';
        }
        
        if (referenceId != null) {
            textBody += 'ReferenceId:  ' + referenceId + '\n';
        }

        if (referenceInfo != null) {
            textBody += 'ReferenceInfo:  ' + referenceInfo + '\n';
        }

        if (ex != null) {
            textBody += 'Exception Type:  ' + ex.getTypeName() + '\n';
            textBody += 'Exception Message:  ' + ex.getMessage() + '\n'; 
            textBody += 'Exception Stack Trace:  ' + ex.getStackTraceString() + '\n';    
        }

        email.setToAddresses(address);
        
        email.setSubject(subject); 
        email.setPlainTextBody(textBody);
        email.setSenderDisplayName('Logger');
        
        messaging.Email[] emails = new messaging.Email[]{email};
        messaging.sendEmail(emails);
    }
}