force-app/main/default/objects/Error_Handling_Configuration__mdt.object
<CustomObject>
    <label>Error Handling Configuration</label>
    <pluralLabel>Error Handling Configurations</pluralLabel>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Email_on_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email on Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Logger__c</fullName>
        <label>Logger</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Object Logger</fullName>
                    <default>true</default>
                    <label>Object Logger</label>
                </value>
                <value>
                    <fullName>Debug Logger</fullName>
                </value>
                <value>
                    <fullName>No Logs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Log_Level__c</fullName>
        <label>Log Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Info</fullName>
                    <label>Info - Info, Error</label>
                </value>
                <value>
                    <fullName>Fine</fullName>
                    <label>Fine - Info,Warning,Error</label>
                </value>
                <value>
                    <fullName>Finest</fullName>
                    <label>Finest - Debug, Info, Warning, Error</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Error_Logs__c.object
<CustomObject>
    <label>Error Logs</label>
    <nameField>
        <displayFormat>Error-{0000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Log_Type__c</fullName>
        <label>Log Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Info</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Debug</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/ApexObjectLoggerTest.cls
@isTest
public class ApexObjectLoggerTest {

    public class LoggerTestException extends Exception {}

    static Error_Handling_Configuration__mdt metadata = new Error_Handling_Configuration__mdt(Logger__c='Object Logger', 
                                                                                              Email_Address__c='arseniys@nubessom.com', 
                                                                                              Email_on_Error__c=true,
                                                                                              MasterLabel='Sandbox');
    static ApexObjectLogger log;
    static Exception ex = new LoggerTestException();
        
    @isTest static void debugShouldWorkOnFinestLogLevel() {       
   
        metadata.Log_Level__c = 'Finest';
        log = new ApexObjectLogger(metadata);
        
        Test.startTest();
        
        log.debug(ex, 'source', '0013F00000IRc4kQAD', 'refInfo', 'msg');
        log.debug(ex, '0013F00000IRc4kQAD', 'refInfo', 'msg');
        log.debug(ex, 'source', 'msg');
        log.debug(ex, 'msg');
        
        log.debug('source', '0013F00000IRc4kQAD', 'refInfo', 'msg');
        log.debug('0013F00000IRc4kQAD', 'refInfo', 'msg');
        log.debug('source', 'msg');
        log.debug('msg');

		List<Error_Logs__c> errorLogs = [SELECT Log_Type__c, 
                                                       Source__c
                                                FROM Error_Logs__c 
                                                WHERE Log_Type__c = 'debug'];
                                          
        System.assertEquals(8, errorLogs.size());

        delete errorLogs;
        
		Test.stopTest();		        
    }

    @isTest static void debugShouldNotWorkOnFineLogLevel() {
        
        metadata.Log_Level__c = 'Fine';
        log = new ApexObjectLogger(metadata);
        
        Test.startTest();
        
        log.debug(ex, 'source', '0013F00000IRc4kQAD', 'refInfo', 'msg');

        List<Error_Logs__c> errorLogs = [SELECT Log_Type__c, 
                                                Source__c
                                         FROM Error_Logs__c 
                                         WHERE Log_Type__c = 'debug'];
        System.assertEquals(0, errorLogs.size());

        delete errorLogs;
        
		Test.stopTest();		        
    }

    @isTest static void debugShouldNotWorkOnInfoLogLevel() {
        metadata.Log_Level__c = 'Info';
        log = new ApexObjectLogger(metadata);
        
        Test.startTest();
        
        log.debug(ex, 'source', '0013F00000IRc4kQAD', 'refInfo', 'msg');

        List<Error_Logs__c> errorLogs = [SELECT Log_Type__c,
                                                Source__c 
                                         FROM Error_Logs__c 
                                         WHERE Log_Type__c = 'debug'];
        System.assertEquals(0, errorLogs.size());

        delete errorLogs;
        
		Test.stopTest();		        
    }
    
    @isTest static void infoShouldWork() {
        log = new ApexObjectLogger(metadata);
        
        Test.startTest();
        log.info(ex, 'source', '0013F00000IRc4kQAD', 'refInfo', 'msg');
        log.info(ex, '0013F00000IRc4kQAD', 'refInfo', 'msg');
        log.info(ex, 'source', 'msg');
        log.info(ex, 'msg');

        log.info('source', '0013F00000IRc4kQAD', 'refInfo', 'msg');
        log.info('0013F00000IRc4kQAD', 'refInfo', 'msg');
        log.info('source', 'msg');
        log.info('msg');

		List<Error_Logs__c> errorLogs = [SELECT Log_Type__c, 
                                                        Source__c 
                                                 FROM Error_Logs__c 
                                                 WHERE Log_Type__c = 'info'];
        System.assertEquals(8, errorLogs.size());

        delete errorLogs;
        
		Test.stopTest();		        
    }
	
    @isTest static void warningShouldWorkOnFinestLogLevel() {
        metadata.Log_Level__c = 'Finest';
        log = new ApexObjectLogger(metadata);

        Test.startTest();
        
        log.warning(ex, 'source', '0013F00000IRc4kQAD', 'refInfo', 'msg');
        log.warning(ex, '0013F00000IRc4kQAD', 'refInfo', 'msg');
        log.warning(ex, 'source', 'msg');
        log.warning(ex, 'msg');

		List<Error_Logs__c> errorLogs = [SELECT Log_Type__c, 
                                                        Source__c 
                                                 FROM Error_Logs__c 
                                                 WHERE Log_Type__c = 'warning'];
        System.assertEquals(4, errorLogs.size());

        delete errorLogs;
        
		Test.stopTest();		        
    }
    
    @isTest static void warningShouldNotWorkOnInfoLogLevel() {
        metadata.Log_Level__c = 'Info';
        log = new ApexObjectLogger(metadata);

        Test.startTest();
        
        log.warning(ex, 'source', '0013F00000IRc4kQAD', 'refInfo', 'msg');

		List<Error_Logs__c> errorLogs = [SELECT Log_Type__c, 
                                                        Source__c 
                                                 FROM Error_Logs__c 
                                                 WHERE Log_Type__c = 'warning']; 
        System.assertEquals(0, errorLogs.size());

        delete errorLogs;
        
		Test.stopTest();		        
    }
    
    @isTest static void errorShouldWork() {
        
        log = new ApexObjectLogger(metadata);

        Test.startTest();
        
        log.error(ex, 'source', '0013F00000IRc4kQAD', 'refInfo', 'msg');
        log.error(ex, '0013F00000IRc4kQAD', 'refInfo', 'msg');
        log.error(ex, 'source', 'msg');
        log.error(ex, 'msg');

		List<Error_Logs__c> errorLogs = [SELECT Log_Type__c, 
                                                        Source__c 
                                                 FROM Error_Logs__c 
                                                 WHERE Log_Type__c = 'error'];
        System.assertEquals(4, errorLogs.size());

        delete errorLogs;
        
		Test.stopTest();		        
    }
}