force-app/main/default/objects/Error_Handling_Configuration__mdt.object
<CustomObject>
    <label>Error Handling Configuration</label>
    <pluralLabel>Error Handling Configurations</pluralLabel>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Email_on_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email on Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Logger__c</fullName>
        <label>Logger</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Object Logger</fullName>
                    <default>true</default>
                    <label>Object Logger</label>
                </value>
                <value>
                    <fullName>Debug Logger</fullName>
                </value>
                <value>
                    <fullName>No Logs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Log_Level__c</fullName>
        <label>Log Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Info</fullName>
                    <label>Info - Info, Error</label>
                </value>
                <value>
                    <fullName>Fine</fullName>
                    <label>Fine - Info,Warning,Error</label>
                </value>
                <value>
                    <fullName>Finest</fullName>
                    <label>Finest - Debug, Info, Warning, Error</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/DebugLoggerTest.cls
@isTest
public class DebugLoggerTest {

    static Exception ex = new LoggerTestException();
    static DebugLogger log;
    
    static Error_Handling_Configuration__mdt metadata = new Error_Handling_Configuration__mdt(Logger__c='Object Logger', 
                                                                                              Email_Address__c='arseniys@nubessom.com', 
                                                                                              Email_on_Error__c=true,
                                                                                              MasterLabel='Sandbox');
    @isTest static void assumeDebugWorksOnFinestLogLevel() {       
   
        metadata.Log_Level__c = 'Finest';
        log = new DebugLogger(metadata);
        
        log.debug(ex, 'source', '0013F00000IRc4kQAD', 'refInfo', 'msg');
        log.debug(ex, '0013F00000IRc4kQAD', 'refInfo', 'msg');
        log.debug(ex, 'source', 'msg');
        log.debug(ex, 'msg');
        
        log.debug('source', '0013F00000IRc4kQAD', 'refInfo', 'msg');
        log.debug('0013F00000IRc4kQAD', 'refInfo', 'msg');
        log.debug('source', 'msg');
        log.debug('msg');
		
        System.assert(true);
    }

    @isTest static void assumeDebugDoesNotWorkOnFineLogLevel() {
        
        metadata.Log_Level__c = 'Fine';
        log = new DebugLogger(metadata);
        
        log.debug(ex, 'source', '0013F00000IRc4kQAD', 'refInfo', 'msg');		
        System.assert(true);
    }

    @isTest static void assumeDebugDoesNotWorkOnInfoLogLevel() {
        metadata.Log_Level__c = 'Info';
        log = new DebugLogger(metadata);
        
        log.debug(ex, 'source', '0013F00000IRc4kQAD', 'refInfo', 'msg');		
        System.assert(true);
    }
    
    @isTest static void assumeInfoWorks() {
        log = new DebugLogger(metadata);
        
        log.info(ex, 'source', '0013F00000IRc4kQAD', 'refInfo', 'msg');
        log.info(ex, '0013F00000IRc4kQAD', 'refInfo', 'msg');
        log.info(ex, 'source', 'msg');
        log.info(ex, 'msg');

        log.info('source', '0013F00000IRc4kQAD', 'refInfo', 'msg');
        log.info('0013F00000IRc4kQAD', 'refInfo', 'msg');
        log.info('source', 'msg');
        log.info('msg');

        System.assert(true);
    }
	
    @isTest static void assumeWarningWorksOnFinestLogLevel() {
        metadata.Log_Level__c = 'Finest';
        log = new DebugLogger(metadata);
      
        log.warning(ex, 'source', '0013F00000IRc4kQAD', 'refInfo', 'msg');
        log.warning(ex, '0013F00000IRc4kQAD', 'refInfo', 'msg');
        log.warning(ex, 'source', 'msg');
        log.warning(ex, 'msg');

		System.assert(true);
    }
    
    @isTest static void assumeWarningDoesNotWorkOnInfoLogLevel() {
        metadata.Log_Level__c = 'Info';
        log = new DebugLogger(metadata);

        log.warning(ex, 'source', '0013F00000IRc4kQAD', 'refInfo', 'msg');
		System.assert(true);
    }
    
    @isTest static void assumeErrorWorks() {
        
        log = new DebugLogger(metadata);
        
        log.error(ex, 'source', '0013F00000IRc4kQAD', 'refInfo', 'msg');
        log.error(ex, '0013F00000IRc4kQAD', 'refInfo', 'msg');
        log.error(ex, 'source', 'msg');
        log.error(ex, 'msg');
		
        System.assert(true);
    }
}